### ISSUE TITLE
Cached dotobj file's AABB values are set to 0

### ISSUE THREAD

**Issue by LJPearson** [JujuAdams/dotobj#5]
If I load a raw dotobj through DotObjModelRawLoad() the AABB values seem to all be set to 0. 

I tested it on the planetcachetest: 

loading the model and doing GetAABB() before the cache is created displays the correct values, then if its cached file is loaded and I do GetAABB() on the cached model the values are 0.

**Comment by JujuAdams** [comment]
Thanks for reporting this, I'll address the problem soon.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/dotobj/commit/3151c4635bca4cb6bd0df3d9794c6d6c15998fad
