### ISSUE TITLE
Unable to get the dotobj example project to run on IDE Version 2.3.1.536 and Runtime 2.3.0.401

### ISSUE THREAD

**Issue by bawat** [JujuAdams/dotobj#6]
I'm running the master branch. https://github.com/JujuAdams/dotobj/tree/master
############################################################################################
ERROR in
action number 1
of Create Event
for object objTransformOnLoadTest:

unable to convert string "dotobj_group" to int64
 at gml_Script_anon_DotobjClassGroup_gml_GlobalScript_DotobjClassGroup_2378_DotobjClassGroup_gml_GlobalScript_DotobjClassGroup (line 108) -         _model.groups_struct[$ name] = self;
############################################################################################
gml_Script_anon_DotobjClassGroup_gml_GlobalScript_DotobjClassGroup_2378_DotobjClassGroup_gml_GlobalScript_DotobjClassGroup (line 108)
gml_Script_DotobjEnsureGroup (line 152) -             AddTo(_model);
gml_Script_DotobjModelLoad (line 84) -     var _group_struct   = DotobjEnsureGroup(_model_struct, __DOTOBJ_DEFAULT_GROUP, 0);
gml_Script_DotobjModelLoadFile (line 31) -     var _result = DotobjModelLoad(_buffer);
gml_Object_objTransformOnLoadTest_Create_0 (line 12) - model_planet = DotobjModelLoadFile("planet.obj");

**Comment by JujuAdams** [comment]
This is a bug in the GMS2.3.0 runtime. You will need to update your version of GameMaker.

If you can recreate this bug in GMS2.3.3 please make a new ticket.
